### ISSUE TITLE
Research CSS

### ISSUE THREAD

**Issue by JordanBehn** [TheDreamTeam-NUBootCamp/Project1#2]
I'm still figuring out how this works

**Comment by Jdoyle5254** [comment]
We are recommending Foundation:


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.6.3/dist/css/foundation.min.css" integrity="sha256-ogmFxjqiTMnZhxCqVmcqTvjfe1Y/ec4WaRj/aQPvn+I=" crossorigin="anonymous">


<script src="https://cdn.jsdelivr.net/npm/foundation-sites@6.6.3/dist/js/foundation.min.js" integrity="sha256-pRF3zifJRA9jXGv++b06qwtSqX1byFQOLjqa2PTEb2o=" crossorigin="anonymous"></script>

**Comment by Jdoyle5254** [comment]
here is the site for Foundations: https://get.foundation/sites/docs/installation.html
