### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by JordanBehn** [TheDreamTeam-NUBootCamp/Project1#4]

**Comment by Jdoyle5254** [comment]
we are opting for a pencil and paper wireframe

**Comment by Jdoyle5254** [comment]
![WireFrame1](https://user-images.githubusercontent.com/69594945/98185752-e4788080-1ed2-11eb-9877-40a20d4f9d7e.jpg)

**Comment by Jdoyle5254** [comment]
This was this initial wireframe I sketched out.
